In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [12]:
data = pd.read_csv('german_credit_data.csv')

In [13]:
data[:5]

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,NaN,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad

In [14]:
data.head()

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
0,0,67,male,2,own,NaN,little,1169,6,radio/TV,good
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
2,2,49,male,1,own,little,NaN,2096,12,education,good
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad

In [15]:
data.shape

(1000, 11)

In [16]:
data=data.dropna()

In [17]:
data

,Unnamed: 0,Age,Sex,Job,Housing,Saving accounts,Checking account,Credit amount,Duration,Purpose,Risk
1,1,22,female,2,own,little,moderate,5951,48,radio/TV,bad
3,3,45,male,2,free,little,little,7882,42,furniture/equipment,good
4,4,53,male,2,free,little,little,4870,24,car,bad
7,7,35,male,3,rent,little,moderate,6948,36,car,good
9,9,28,male,3,own,little,moderate,5234,30,car,bad
10,10,25,female,2,rent,little,moderate,1295,12,car,bad
11,11,24,female,2,rent,little,little,4308,48,business,bad
12,12,22,female,2,own,little,moderate,1567,12,radio/TV,good
13,13,60,male,1,own,little,little,1199,24,car,bad
14,14,28,female,2,rent,little,little,1403,15,car,good
15,15,32,female,1,own,moderate,little,1282,24,radio/TV,bad
18,18,44,female,3,free,little,moderate,12579,24,car,bad
21,21,44,male,2,rent,quite rich,little,2647,6,radio/TV,good
22,22,48,male,1,rent,little,little,2241,10,car,good
23,23,44,male,2,own,moderate,moderate,1804,12,car,good
25,25,36,male,1,own,little,little,1374,6,furniture/equipment,good
27,27,42,female,2,rent,rich,rich,409,12,radio/TV,good
28,28,34,male,2,own,little,moderate,2415,7,radio/TV,good
29,29,63,male,2,own,little,little,6836,60,business,bad
30,30,36,male,2,own,rich,moderate,1913,18,business,good
31,31,27,male,2,own,little,little,4020,24,furniture/equipment,good
32,32,30,male,2,own,moderate,moderate,5866,18,car,good
34,34,33,female,3,own,little,rich,1474,12,furniture/equipment,good
35,35,25,male,1,own,little,moderate,4746,45,radio/TV,bad
37,37,37,male,2,own,little,rich,2100,18,radio/TV,bad
38,38,37,male,2,own,little,rich,1225,10,domestic appliances,good
39,39,24,male,2,own,little,moderate,458,9,radio/TV,good
41,41,26,male,2,own,quite rich,moderate,1158,12,radio/TV,good
42,42,44,male,1,own,little,moderate,6204,18,repairs,good
43,43,24,male,2,rent,moderate,little,6187,30,car,good
...,...,...,...,...,...,...,...,...,...,...,...
946,946,30,male,2,free,quite rich,little,3349,24,furniture/equipment,bad
950,950,40,male,0,own,little,moderate,3590,18,business,good
951,951,24,male,2,own,little,little,2145,36,business,bad
952,952,28,female,2,rent,quite rich,moderate,4113,24,car,bad
954,954,29,female,2,own,little,little,1893,12,car,good
955,955,57,female,3,rent,rich,little,1231,24,radio/TV,good
957,957,37,male,1,own,little,moderate,1154,9,radio/TV,good
958,958,45,male,1,own,little,little,4006,28,car,bad
959,959,30,male,2,free,moderate,moderate,3069,24,furniture/equipment,good
961,961,47,male,2,own,little,moderate,2353,21,car,good
964,964,22,male,1,own,little,moderate,454,6,repairs,good
966,966,23,male,1,own,quite rich,moderate,2520,27,radio/TV,bad
969,969,40,male,1,own,little,little,3939,11,car,good
970,970,22,male,2,own,moderate,moderate,1514,15,repairs,good
972,972,29,female,0,rent,little,little,1193,24,car,bad
973,973,36,male,2,rent,little,little,7297,60,business,bad
975,975,57,female,1,own,quite rich,rich,1258,24,radio/TV,good
976,976,64,female,2,own,little,moderate,753,6,radio/TV,good
979,979,25,male,2,rent,moderate,moderate,1264,15,car,bad
980,980,49,male,2,own,little,moderate,8386,30,furniture/equipment,bad
982,982,28,female,3,own,moderate,rich,2923,21,car,good
983,983,26,male,2,own,little,little,8229,36,car,bad
985,985,25,female,2,rent,little,little,1433,15,furniture/equipment,good
986,986,33,male,2,own,little,rich,6289,42,business,good
988,988,29,male,3,free,little,little,6579,24,car,good
989,989,48,male,1,own,little,moderate,1743,24,radio/TV,good
993,993,30,male,3,own,little,little,3959,36,furniture/equipment,good
996,996,40,male,3,own,little,little,3857,30,car,good
998,998,23,male,2,free,little,little,1845,45,radio/TV,bad
999,999,27,male,2,own,moderate,moderate,4576,45,car,good